# Generated by Django 4.2.16 on 2024-11-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SynChronisApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachertable',
            name='age',
        ),
        migrations.AddField(
            model_name='teachertable',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
