# Generated by Django 4.2.16 on 2024-11-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SynChronisApp', '0002_remove_teachertable_age_teachertable_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancetable',
            name='attendance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancetable',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studenttable',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studenttable',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studenttable',
            name='guardian_phone_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studenttable',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
