# Generated by Django 4.2.16 on 2024-11-29 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SynChronisApp', '0007_timetable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancetable',
            old_name='attendance',
            new_name='Attendance',
        ),
        migrations.RenameField(
            model_name='attendancetable',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='attendancetable',
            old_name='status',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='classtable',
            old_name='department',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='classtable',
            old_name='year',
            new_name='Year',
        ),
        migrations.RenameField(
            model_name='studenttable',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='studenttable',
            old_name='admission_no',
            new_name='Admission_no',
        ),
        migrations.RenameField(
            model_name='studenttable',
            old_name='age',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='studenttable',
            old_name='blood_group',
            new_name='Blood_group',
        ),
        migrations.RenameField(
            model_name='studenttable',
            old_name='date_of_birth',
            new_name='Date_of_birth',
        ),
        migrations.RenameField(
            model_name='studenttable',
            old_name='department',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='studenttable',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='studenttable',
            old_name='gender',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='studenttable',
            old_name='guardian_name',
            new_name='Guardian_name',
        ),
        migrations.RenameField(
            model_name='studenttable',
            old_name='guardian_phone_number',
            new_name='Guardian_phone_number',
        ),
        migrations.RenameField(
            model_name='studenttable',
            old_name='guardian_relation',
            new_name='Guardian_relation',
        ),
        migrations.RenameField(
            model_name='studenttable',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='studenttable',
            old_name='phone_number',
            new_name='Phone_number',
        ),
        migrations.RenameField(
            model_name='studenttable',
            old_name='year',
            new_name='Year',
        ),
        migrations.RenameField(
            model_name='teachertable',
            old_name='department',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='teachertable',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='teachertable',
            old_name='gender',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='teachertable',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='teachertable',
            old_name='phone_number',
            new_name='Phone_number',
        ),
        migrations.RenameField(
            model_name='teachertable',
            old_name='qualification',
            new_name='Qualification',
        ),
        migrations.RenameField(
            model_name='teachertable',
            old_name='subject',
            new_name='Subject',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='semester',
            new_name='Semester',
        ),
        migrations.CreateModel(
            name='LocationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('Location_name', models.CharField(blank=True, max_length=50, null=True)),
                ('TEACHER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SynChronisApp.teachertable')),
            ],
        ),
    ]
