# Generated by Django 4.2.16 on 2024-11-30 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SynChronisApp', '0009_remove_locationtable_teacher_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TimeTable',
            new_name='TimeTableTable',
        ),
    ]
