# Generated by Django 4.2.16 on 2024-11-30 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SynChronisApp', '0010_rename_timetable_timetabletable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classtable',
            old_name='class_name',
            new_name='Class_name',
        ),
        migrations.RenameField(
            model_name='classtable',
            old_name='latitude',
            new_name='Latitude',
        ),
        migrations.RenameField(
            model_name='classtable',
            old_name='longitude',
            new_name='Longitude',
        ),
    ]
