# Generated by Django 4.2.16 on 2024-11-30 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SynChronisApp', '0011_rename_class_name_classtable_class_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject_name', models.CharField(blank=True, max_length=50, null=True)),
                ('Semester', models.CharField(blank=True, max_length=50, null=True)),
                ('Class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SynChronisApp.classtable')),
                ('Teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SynChronisApp.teachertable')),
            ],
        ),
    ]
