# Generated by Django 4.2.16 on 2024-12-03 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SynChronisApp', '0012_subjecttable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjecttable',
            name='Semester',
        ),
        migrations.RemoveField(
            model_name='timetabletable',
            name='Semester',
        ),
        migrations.AddField(
            model_name='classtable',
            name='Semester',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='NotesTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unit', models.CharField(blank=True, max_length=50, null=True)),
                ('Notes', models.CharField(blank=True, max_length=50, null=True)),
                ('Class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SynChronisApp.classtable')),
                ('Subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SynChronisApp.subjecttable')),
                ('Teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SynChronisApp.teachertable')),
            ],
        ),
    ]
