# Generated by Django 4.2.16 on 2024-12-03 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SynChronisApp', '0013_remove_subjecttable_semester_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notice', models.CharField(blank=True, max_length=50, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SynChronisApp.teachertable')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApplicationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('Reason', models.CharField(blank=True, max_length=50, null=True)),
                ('Status', models.CharField(blank=True, max_length=50, null=True)),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SynChronisApp.studenttable')),
            ],
        ),
    ]
