# Generated by Django 4.2.16 on 2024-12-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SynChronisApp', '0015_studentnoticetable_teachernoticetable_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachernoticetable',
            old_name='Notice',
            new_name='Notice_Content',
        ),
        migrations.AddField(
            model_name='studentnoticetable',
            name='File_Attachment',
            field=models.FileField(blank=True, max_length=50, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='teachernoticetable',
            name='File_Attachment',
            field=models.FileField(blank=True, max_length=50, null=True, upload_to=''),
        ),
    ]
