# Generated by Django 4.2.16 on 2024-12-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SynChronisApp', '0016_rename_notice_teachernoticetable_notice_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachernoticetable',
            name='Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='teachernoticetable',
            name='File_Attachment',
            field=models.FileField(blank=True, null=True, upload_to='File/'),
        ),
    ]
