# Generated by Django 4.2.16 on 2024-12-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SynChronisApp', '0017_alter_teachernoticetable_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetabletable',
            name='EndTime',
            field=models.TimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='timetabletable',
            name='StarTime',
            field=models.TimeField(blank=True, max_length=50, null=True),
        ),
    ]
