# Generated by Django 4.2.16 on 2024-12-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SynChronisApp', '0022_rename_startime_timetabletable_starttime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjecttable',
            old_name='Teacher',
            new_name='TeacherName',
        ),
        migrations.RemoveField(
            model_name='subjecttable',
            name='Class_name',
        ),
        migrations.AddField(
            model_name='subjecttable',
            name='Course',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subjecttable',
            name='Semester',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subjecttable',
            name='Year_of_Syllabus',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetabletable',
            name='EndTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetabletable',
            name='StartTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
